# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24674af1c5fb87337b0c63faa684aa8e3d3cd3f9ed49e10944d4f7c43b84b73f5fbfb69ec6003758a7c4edc1f07d000ffc535fe5b7ee29b874fb1f60ecb9a4a6

test:
  secret_key_base: 6b3fda3d2701137023e1c0eea835b9205a9870c34f1fc2d931737dc4d34bc7106de80dd82c2c96ac5496e48354f62ad7259ae58bb15886bca121261752ba8dec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
